version: '3.8'

services:
  app:
    build:
      context: ./server
      dockerfile: Dockerfile
    container_name: jain-app-backend
    restart: unless-stopped
    ports:
      - "4000:4000"
    environment:
      - NODE_ENV=production
      - PORT=4000
      - MONGODB_URI=mongodb://mongodb:27017/jainapp
      - SESSION_SECRET=jainprabhutmanch-secret-key
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    volumes:
      - ./server:/usr/src/app
      - /usr/src/app/node_modules
    depends_on:
      - mongodb
      - redis

  mongodb:
    image: mongo:6
    container_name: jain-mongodb
    restart: unless-stopped
    volumes:
      - mongodb_data:/data/db
    ports:
      - "27017:27017"

  redis:
    image: redis:alpine
    container_name: jain-redis
    restart: unless-stopped
    volumes:
      - redis_data:/data
    ports:
      - "6379:6379"

volumes:
  mongodb_data:
  redis_data: